[package]
name = "halcyon"
version = "0.1.0"
edition = "2024"
authors = ["Petr Šácha <petrsacha@proton.me>"]
description = "SDL3 wrapper with QoL additions"
repository = "https://github.com/lyorig/halcyon-rs"
license = "MIT"
keywords = ["gamedev", "sdl", "graphics"]
categories = ["graphics", "gui", "api-bindings", "rendering"]

# Disables testing `src/lib.rs`, since there are no tests there.
# The actual tests are located in `test/` (see [[test]] below).
[lib]
test = false

[dependencies]
bitflags = "2.13.1"
paste = "1.0.15"
sdl3-sys = "0.6.5"
sdl3-ttf-sys = "0.6.0"

[dev-dependencies]
rustest = "0.3.1"
tobj = "4.0.5"

[profile.release-max]
inherits = "release"
panic = "abort"
lto = "fat"
codegen-units = 1
strip = true

[[test]]
name = "haltest"
path = "test/main.rs"
harness = false
